# Generated by Django 4.2.7 on 2023-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=100)),
                ('projectDescription', models.TextField(max_length=500)),
                ('additionalInformation', models.TextField(max_length=500)),
                ('phoneNumber', models.CharField(max_length=12)),
            ],
        ),
    ]
